package nz.ac.auckland.pokemon.dto;

import nz.ac.auckland.pokemon.domain.Gender;
import nz.ac.auckland.pokemon.domain.GeoPosition;
import nz.ac.auckland.pokemon.domain.Move;
import nz.ac.auckland.pokemon.domain.Trainer;
import nz.ac.auckland.pokemon.jaxb.DateTimeAdapter;
import nz.ac.auckland.pokemon.jaxb.LocalDateAdapter;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.joda.time.DateTime;
import org.joda.time.LocalTime;

import javax.persistence.Enumerated;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.util.Date;
import java.util.Set;

/* Class to represent a Trainer.
 *
 * An instance of this class represents a DTO Trainer
 *
 */

@XmlRootElement(name="pokemon")
@XmlAccessorType(XmlAccessType.FIELD)
public class BattleDTO {

	@XmlAttribute(name="id")
	private long id;

	@XmlElement(name="startTime")
	@XmlJavaTypeAdapter(value=DateTimeAdapter.class)
	private DateTime startTime;

	@XmlElement(name="endTime")
	@XmlJavaTypeAdapter(value=DateTimeAdapter.class)
	private DateTime endTime;

	@XmlElement(name="firstTrainer")
	private TrainerDTO firstTrainer;

	@XmlElement(name="secondTrainer")
	private TrainerDTO secondTrainer;

	@XmlElement(name="winnerId")
	private long winnerId;
	
	@XmlElement(name="location")
	private GeoPosition location;

	protected BattleDTO() {

	}

	/**
	 * Constructs a DTO Trainer instance. This method is intended to be called
	 * by Web service clients when creating new Trainers. The id field is not
	 * required because it is generated by the Web service. Similarly, the
	 * last-known-position field is not required. Of the constructor's
	 * parameters, all fields must be non-null with the exception of curfew,
	 * which is optional (not all Trainers are subject to a curfew).
	 *
	 */
	public BattleDTO(DateTime startTime, DateTime endTime, TrainerDTO firstTrainer, TrainerDTO secondTrainer,
			long winnerId, GeoPosition location) throws IllegalArgumentException {
		this(0, startTime, endTime, firstTrainer, secondTrainer, winnerId, location);
	}

	/**
	 * Constructs a DTO Parolee instance. This method should NOT be called by
	 * Web Service clients. It is intended to be used by the Web Service
	 * implementation when creating a DTO Parolee from a domain-model Parolee
	 * object.
	 */
	public BattleDTO(long id, DateTime startTime, DateTime endTime, TrainerDTO firstTrainer, TrainerDTO secondTrainer, 
			long winnerId, GeoPosition location) {
		this.id = id;
		this.startTime = startTime;
		this.endTime = endTime;
		this.firstTrainer = firstTrainer;
		this.secondTrainer = secondTrainer;
		this.winnerId = winnerId;
		this.location = location;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public DateTime getStartTime() {
		return startTime;
	}

	public void setStartTime(DateTime startTime) {
		this.startTime = startTime;
	}

	public DateTime getEndTime() {
		return endTime;
	}

	public void setEndTime(DateTime endTime) {
		this.endTime = endTime;
	}

	public TrainerDTO getFirstTrainer() {
		return firstTrainer;
	}

	public void setFirstTrainer(TrainerDTO firstTrainer) {
		this.firstTrainer = firstTrainer;
	}

	public TrainerDTO getSecondTrainer() {
		return secondTrainer;
	}

	public void setSecondTrainer(TrainerDTO secondTrainer) {
		this.secondTrainer = secondTrainer;
	}


	public long getWinnerId() {
		return winnerId;
	}

	public void setWinnerId(long winnerId) {
		this.winnerId = winnerId;
	}

    public GeoPosition getLocation() {
    	return location;
    }
    
    public void setLocation(GeoPosition location) {
    	this.location = location;
    }
	
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		
		buffer.append("Battle: { [");
		buffer.append(id);
		buffer.append("]; ");
		buffer.append(firstTrainer.getLastName());
		buffer.append(", ");
		buffer.append(secondTrainer.getLastName());
		buffer.append(" }");
		
		return buffer.toString();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof BattleDTO))
			return false;
		if (obj == this)
			return true;

		BattleDTO rhs = (BattleDTO) obj;
		return new EqualsBuilder().
			append(id, rhs.id).
			append(firstTrainer.getFirstName(), rhs.firstTrainer.getFirstName()).
			append(secondTrainer.getFirstName(), rhs.secondTrainer.getFirstName()).
			append(startTime, rhs.startTime).
			append(endTime, rhs.endTime).
			isEquals();
	}
	
	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 31).
				append(id).
				append(firstTrainer.getFirstName()).
				append(secondTrainer.getFirstName()).
				append(startTime).
				append(endTime).
				toHashCode();
	}
}


